### PR TITLE
Add a check for if user is a member of a community

### PR DESCRIPTION
**Pull request by peteclodi**

### CODE REVIEW

**Comment by peteclodi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;nIhzvKNc&#x2F;205-1-error-messaging-when-a-logged-in-student-who-is-not-a-member-of-a-community-tries-to-post-in-a-that-community"> (1) Error messaging when a logged in student who is NOT a member of a community tries to post in a that community</a>

**Comment by karllhughes** [comment]
@peteclodi is this ready to be reviewed? Do you mind fixing the conflicts before I do. Thanks!

**Comment by peteclodi** [comment]
It might be ready. I'm still working through the Unit Tests and have
already uncovered one bug. I will resolve the conflicts before putting it
back into review.

On Thu, May 12, 2016 at 8:12 AM, Karl L. Hughes <notifications@github.com>
wrote:

> @peteclodi <https://github.com/peteclodi> is this ready to be reviewed?
> Do you mind fixing the conflicts before I do. Thanks!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/packbackbooks/packback-services/pull/37#issuecomment-218752533>
>



-- 
Pete Clodi
pete@packback.co

**Comment by peteclodi** [comment]
@karllhughes This is ready for review

**Pull request merged**
