### PR TITLE
Max recent user activity

### PR DESCRIPTION
**Pull request by peteclodi**

### CODE REVIEW

**Comment by peteclodi** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;W6WvkWIO&#x2F;291-0-5-show-50-items-per-page-on-pbq-instead-of-10"> (0.5) Show 50 items per page on PBQ instead of 10</a>

**Comment by karllhughes** [comment]
@peteclodi this one has a conflict now. I think that's my bad for doing the wrong order.

**Comment by peteclodi** [comment]
OK, I'll take care of it

On Wed, Jun 8, 2016 at 8:55 AM, Karl L. Hughes <notifications@github.com>
wrote:

> @peteclodi <https://github.com/peteclodi> this one has a conflict now. I
> think that's my bad for doing the wrong order.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/packbackbooks/packback-services/pull/45#issuecomment-224596379>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AFoBC2QDR5338zWhwnteZaxK33pP44ADks5qJsncgaJpZM4IwZbz>
> .
>



-- 
Pete Clodi
pete@packback.co

**Comment by peteclodi** [comment]
@karllhughes Can be merged

**Pull request merged**
