### PR TITLE
Adding eager loading parameters to communities-related requests

### PR DESCRIPTION
**Pull request by EricTendian**
When reviewing this, make sure to verify that I'm not missing any places where we need to include the counts or attributes - I think I got all of them, but could use a second look.

### CODE REVIEW

**Comment by EricTendian** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;xwEotTeI&#x2F;66-1-update-api-calls-in-frontend-to-load-community-attributes"> (1) Update API calls in Frontend to load community attributes</a>

**Comment by peteclodi** [comment]
@EricTendian We shouldn't hard-code these values into the services. There may be times when we want them and times we don't, which is the point of breaking them out into includes in the first place. I created PR #10 that addresses the include issue for the single community and paginated communities endpoints. The responsibility for adding these includes is on the caller of these functions, so that they can include only the values they need/want.

The proper solution is to enhance the service functions to allow a variable include value to be passed; and then the clients, questions and admin, would be responsible for passing these include values.

**Comment by EricTendian** [comment]
@peteclodi good point - I merged the changes from that branch into this one, so now I just added includes to the `getStudentsCommunities` function. Once your PR gets merged then this one can be reviewed/merged.

**Comment by EricTendian** [comment]
@peteclodi it looks like there's not really anything new in this PR after I merged your changes in. Going to close it and delete my branch.

**Pull request closed without merging**
