### PR TITLE
Adding optional redirect and login urls to service

### PR DESCRIPTION
**Pull request by karllhughes**
The two parameters I have added here are optional. The backend will default to use the packbackbooks.com marketing URLs that we've already been using if you don't pass anything in. But, we need a way to pass these params in for the questions project: https://www.vivifyscrum.com/#/boards/4065/sprint-backlog?task=SE1-457

Another PR will follow with an update to the Questions Frontend.

### CODE REVIEW

**Comment by karllhughes** [comment]
@peteclodi I assume you'll have to deploy this after it's approved. I don't really know what that entails or if bower does it automatically?

**Comment by peteclodi** [comment]
@karllhughes I think that we should control the redirect URLs on the server-side. This will allow us to change redirect URLs and add new URLs without having to modify the front-end. The front-end could just pass its type, i.e. 'marketing'/'', 'questions' or 'admin'. This will keep the front-end out of the decision making process while allowing us to come up with schemes on the back-end that could allow us to update the URLs if we need.

**Comment by karllhughes** [comment]
@peteclodi that's probably a good idea. I'll modify both this PR and https://github.com/packbackbooks/questions-frontend/pull/115

**Comment by karllhughes** [comment]
@peteclodi i've updated this based on your thoughts. Now you can just pass in an application_name parameter (either `marketing` or `questions_fe` will work).

**Pull request merged**
